name: Build

on:
  push:
#    branches:
#    - master
    tags:
    - '*'

    paths-ignore:
    - ".vscode/**"
    - ".github/**"

jobs:
  build:
    strategy:
      matrix:
        type: [retail] #[retail, cata, wrath, classic]
        include:
          - type: retail
            pkgmeta: .pkgmeta
#          - type: cata
#            pkgmeta: .pkgmeta_cata
#          - type: wrath
#            pkgmeta: .pkgmeta_wrath
#          - type: classic
#            pkgmeta: .pkgmeta_vanilla

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: BigWigsMods/packager@master
      with:
        args: -p 1229505 -a qGYMEvGg -w 26919 -g ${{matrix.type}} -m ${{matrix.pkgmeta}}
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}