name: Release

on:
  push:
    tags:
    - '*'
    paths-ignore:
    - ".vscode/**"
    - ".github/**"
    - ".release/**"

jobs:
  build:
    strategy:
      matrix:
        type: [retail]
        include:
          - type: retail
            pkgmeta: .pkgmeta

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Lua Check
      uses: BigWigsMods/actions/luacheck@master
      with:
        args: -q

    - name: Package
      uses: BigWigsMods/packager@master
      with:
        args: -p 1229505 -a qGYMEvGg -w 26919 -g ${{matrix.type}} -m ${{matrix.pkgmeta}}
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}